export const skill = [
	{ value: 'HTML', label: 'HTML' },
	{ value: 'CSS', label: 'CSS' },
	{ value: 'Javascript', label: 'Javascript' },
	{ value: 'React', label: 'React' },
	{ value: 'Angular', label: 'Angular' },
	{ value: 'jQuery', label: 'jQuery' },
	{ value: 'NodeJS', label: 'NodeJS' },
	{ value: 'Python', label: 'Python' },
	{ value: 'PHP', label: 'PHP' },
	{ value: 'Ruby On Rails', label: 'Ruby On Rails' },
	{ value: 'SQL', label: 'SQL' },
	{ value: 'BackboneJS', label: 'BackboneJS' },
	{ value: 'Web Design', label: 'Web Design' },
	{ value: 'Project management', label: 'Project management' },
	{ value: 'Git', label: 'Git' },
	{ value: 'Docker', label: 'Docker' },
	{ value: 'AWS Lambda', label: 'AWS Lambda' },
	{ value: 'Firebase', label: 'Firebase' },
];
export const languages = [
	{ value: 'en', label: 'English, EN' },
	{ value: 'fr', label: 'French, FR' },
	{ value: 'es', label: 'Spanish, ES' },
	{ value: 'ar', label: 'Arabic, AR' },
	{ value: 'cmn', label: 'Mandarin, CMN' },
	{ value: 'ru', label: 'Russian, RU' },
	{ value: 'pt', label: 'Portuguese, PT' },
	{ value: 'de', label: 'German, DE' },
	{ value: 'ja', label: 'Japanese, JA' },
	{ value: 'hi', label: 'Hindi, HI' },
	{ value: 'ms', label: 'Malay ,MS' },
	{ value: 'fa', label: 'Persian, FA' },
	{ value: 'sw', label: 'Swahili, SW' },
	{ value: 'ta', label: 'Tamil, TA' },
	{ value: 'it', label: 'Italian, IT' },
	{ value: 'nl', label: 'Dutch, NL' },
	{ value: 'tr', label: 'Turkish, TR' },
	{ value: 'vi', label: 'Vietnamese, VI' },
	{ value: 'pl', label: 'Polish, PL' },
	{ value: 'jv', label: 'Javanese, JV' },
	{ value: 'pa', label: 'Punjabi, PA' },
	{ value: 'th', label: 'Thai, TH' },
	{ value: 'ko', label: 'Korean, KO' },
];
